routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware('auth')->group(function () {
    Route::resource('sections', 'SectionController');
    Route::resource('users', 'UserController');

});

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $logo
 * @property  $users
 */
class Section extends Model
{
   protected $table  = 'sections',
            $fillable = [
                'name',
                'description',
                'logo',
   ];

    /**
     * Пользователи, принадлежащие к секциям.
     */
    public function users()
    {
        return $this->belongsToMany('App\User', 'users_sections');
    }

    public function usersSections()
    {
        return $this->hasMany('App\Models\UsersSection');
    }
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Section;
use \App\User;
use Faker\Provider\File;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sections = Section::paginate(10);
        return view('sections.index', compact('sections'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::select('id','name', 'email')->get();
        return view('sections.create', compact('users'));
    }
    /**
     * Store a newly created resource in storage.
     *Запись секции
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
            'logo' => 'required|image|mimes:jpeg,png,jpg,svg|max:2048',
            'users' => 'required',
        ]);
        //Валидация, определение путей
        $imageName = $request->file('logo')->getClientOriginalName();
        //Сохраняем изображение, затем записываем в базу данные
        $section = Section::create([
            'name' => $request->get('name'),
            'description'=> $request->get('description'),
            'logo'=> $imageName,
        ]);
        //ЗАпись изображения
        $request->file('logo')->move(storage_path('app\logo\\'.$section->id), $imageName);
        //получение id выбранных пользователей и запись
        $usersId =  array_keys($request->post('users'));
        $section->users()->attach($usersId);

        return redirect('/sections')->with('success', 'Section has been added');
    }
    /**
    * Show a newly created resource in storage.
    *
    * Show a resource.
    * @param \App\Models\Section $section
    * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {
        return view('sections.show', compact('section'));
    }
    /**
     * Edit the form for editing the specified resource.
     *
     * страница редактирования(В ЮИ я привык делать рендерм формы обновления  и функционал в одном методе)
     * @param \App\Models\Section $section
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {
        $users_id = $section->users()->pluck('user_id')->toArray();
        $users = User::select('id','name', 'email')->whereNotIn('id', $users_id)->get()->toArray();
        return view('sections.edit', compact('section','users'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Section  $section
     * Обновляем данные секции
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
            'users' => 'required'
        ]);
        $imageName = $request->file('logo')->getClientOriginalName();
        $section->name = $request->get('name');
        $section->description = $request->get('description');
        $section->logo = $imageName;
        if($request->file('logo')){
            $request->validate(['logo' => 'required|image|mimes:jpeg,png,jpg,svg|max:2048']);
            if($request->file('logo')->move(storage_path('app\logo\\'.$section->id), $imageName)){
                $deletePath = storage_path('app\logo\\'.$section->id.'\\'.$section->logo);
                File::delete($deletePath);
                $section->logo = $imageName;
            }
        }
        //Вытаскиваем идентификаторы, затем синхронизируем с записью
        $usersId =  array_keys($request->post('users'));
        $section->users()->sync($usersId);
        if($section->save())
            return redirect('/sections')->with('success', 'Section has been updated');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  Section $section
     * @return \Illuminate\Http\Response
     */
    public function destroy(Section $section)
    {
        $section->delete();
        return redirect('/sections')->with('success', 'Section has been deleted Successfully');
    }
}

resources/views/sections/create.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Add Section
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form enctype="multipart/form-data" method="post" action="{{ route('sections.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name" required/>
                </div>
                <div class="form-group">
                    <label for="description">Description :</label>
                    <textarea  class="form-control" name="description" placeholder="Enter Descrtiption" rows="9" required>
                    </textarea>
                </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="validatedCustomFile" name="logo" accept=".png, .jpg, .jpeg, .svg" required>
                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                        <div class="invalid-feedback">Example invalid custom file feedback</div>
                    </div>
                @if ($users)
                    <div>
                        <h2 class="mt-2 mb-2">Users</h2>
                        @foreach($users as $user)
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" name="users[{{$user->id}}]"  id="user-{{$user->id}}">
                                    <label class="form-check-label" for="user-{{$user->id}}">{{$user->name}} ( <span class="text-primary">{{$user->email}}</span> )</label>
                                </div>
                        @endforeach
                    </div>
                @endif
                <button type="submit" class="btn btn-primary mt-3">Add</button>
            </form>
        </div>
    </div>
@endsection

resources/views/sections/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Edit Share
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form enctype="multipart/form-data"  method="post" action="{{ route('sections.update', $section->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name" value="{{$section->name}}" required/>
                </div>
                <div class="form-group">
                    <label for="description">Description :</label>
                    <textarea  class="form-control" name="description" value="{{$section->description}}" placeholder="Enter Descrtiption" rows="9" required>
                    </textarea>
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="validatedCustomFile" name="logo" accept=".png, .jpg, .jpeg, .svg" required>
                    <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                    <div class="invalid-feedback">Example invalid custom file feedback</div>
                </div>
                @if ($section->users)
                    <div>
                        <h2 class="mt-2 mb-2">Users</h2>
                        @foreach($section->users as $user)
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" checked name="users[{{$user->id}}]"  id="user-{{$user->id}}">
                                <label class="form-check-label" for="user-{{$user->id}}">{{$user->name}} ( <span class="text-primary">{{$user->email}}</span> )</label>
                            </div>
                        @endforeach
                        @foreach($users as $user)
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="users[{{$user['id']}}]"  id="user-{{$user['id']}}">
                                <label class="form-check-label" for="user-{{$user['id']}}">{{$user['name']}} ( <span class="text-primary">{{$user['email']}}</span> )</label>
                            </div>
                        @endforeach
                    </div>
                @endif
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
                <a href="{{ route('sections.index')}}" class="btn btn-success">Back</a>
        </div>
    </div>
@endsection

resources/views/sections/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif
      <div class="card-header">
          Add Section
      </div>
  <table class="table table-striped">
    <tbody>
        @if ($sections)
            @foreach($sections as $section)
                    <tr>
                        <td><img src="{{asset('storage/app/logo/'.$section->id.'/'.$section->logo)}}" alt=""></td>
                        <td>
                            <strong>{{$section->name}}</strong>
                            <p>{{$section->description}}</p>
                        </td>
                        <td>
                            <strong>Users</strong>
                            @foreach($section->users as $user)
                                <p>{{$user->name}}</p>
                            @endforeach
                        </td>
                        <td><a href="{{ route('sections.edit', $section->id)}}" class="btn btn-primary">Edit</a></td>
                        <td>
                            <form action="{{ route('sections.destroy', $section->id)}}" method="post">
                              @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
            @endforeach
        @endif
    </tbody>
  </table>
<div>
{{ $sections->links() }}
@endsection